### ISSUE TITLE
Env vars visible at build time

### ISSUE THREAD

**Issue by SebastienLinker** [actions/container-action#7]
Hi,

Is it possible to pass environment variables to the `docker build` command? 
I have some variables like CUDA version, library xyz version, ... and would like to access it during the `docker build` step. With the `env` or `args` options,  I can access it during the `run` step, but not while the image is being built.

Installing the whole thing in `docker run` does not make a big difference on the result, but I'd like to leverage docker cache

**Comment by SInnget** [comment]
> Hi,
> 
> Is it possible to pass environment variables to the `docker build` command?
> I have a key stored in github secrets and would like to access it during the `docker build` step. With the `env` or `args` options, I can access it during the `run` step, but not while the image is being built.

yes, via `--build-args` 
[check this](https://paper.dropbox.com/doc/Pip-install-our-private-repos-GITTOKEN--BGIGxlNnh8DR~HqT6nY0zIGPAg-MCqLecmJsT0JxjIHLezpV#:uid=037028791239645448866491&h2=Install-package-inside-docker)

**Comment by guyer** [comment]
What is [`run.env`](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsenv) if not for this? But it doesn't seem to work.

**Comment by ncalteen** [comment]
Hello! Apologies for the delay in responding to this issue. Could you tell me how you're running the build? For example, if you're building the container using the [`docker/build-push-action`](https://github.com/docker/build-push-action/tree/v4/) action, then you would need to set any environment variables at a level where this step would see them. If you set the environment variable at the job level, then any steps within that job would see the value.

```yaml
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    env:
      CUDA_VERSION: 1.2.3

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Setup Docker BuildX
        id: setup-buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
```
